# Generated by Django 3.2.6 on 2021-08-30 04:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ('created_time',),
            },
        ),
        migrations.AlterField(
            model_name='figures',
            name='elevation',
            field=models.PositiveBigIntegerField(verbose_name='Elevation'),
        ),
        migrations.AlterField(
            model_name='figures',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='figures',
            name='lon',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude'),
        ),
    ]
