# Generated by Django 3.2.6 on 2021-08-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210830_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='figures',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web.Tag'),
        ),
    ]
