# Generated by Django 3.2.6 on 2021-08-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210831_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souffle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
        migrations.AlterField(
            model_name='sphere',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
        migrations.AlterField(
            model_name='sphere',
            name='object_type',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Object type'),
        ),
    ]
