# Generated by Django 3.2.6 on 2021-08-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210831_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='souffle',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='sphere',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, verbose_name='slug'),
        ),
    ]
