# Generated by Django 3.2.6 on 2021-08-29 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Category',
                'db_table': 'Category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('elevation', models.PositiveBigIntegerField(verbose_name='Altitude')),
                ('altitude', models.PositiveBigIntegerField(verbose_name='Altitude')),
                ('object_type', models.SmallIntegerField(verbose_name='Object type')),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Latitude')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
            options={
                'verbose_name_plural': 'Figures',
                'db_table': 'Figures',
                'ordering': ('created_time',),
            },
        ),
    ]
